### PR TITLE
Checking if OVER_QUERY_LIMIT is caused because Daily limit

### PR DESCRIPTION
**Pull request by Ismamai**
Checking if OVER_QUERY_LIMIT is caused because Daily limit. In that case throw OverDailyLimitException

### CODE REVIEW

**Comment by Ismamai** [comment]
Created for https://github.com/googlemaps/google-maps-services-java/issues/156

**Comment by domesticmouse** [comment]
Hey Ismamai, I can't accept this PR until after you sign the CLA. I'm not going to review this PR until after you have signed. Thanks!

**Comment by Ismamai** [comment]
I already signed the CLA few months ago

**Comment by Ismamai** [comment]
I signed it!

**Comment by domesticmouse** [comment]
My internal systems are showing no matching CLA declarations on file for your GitHub username. Can you get over to https://cla.developers.google.com/clas and sign it again?

**Comment by Ismamai** [comment]
How can I see what username these commits were done. When I go to the clas page I see that I am covered by the agreement

We don't have any individual agreements on file for you.

Corporate Agreements

You are covered by the following corporate agreements:
xxxxxxxxx

**Comment by domesticmouse** [comment]
Can you email me (brettmorgan@google.com) with the details of which corporate agreement you are covered by? Also, which account you are logged into cla.developers.google.com as? I need to chase up internal teams to figure out what has broken...

**Comment by domesticmouse** [comment]
I believe this was covered in #188. Thanks @Ismamai =)

**Pull request closed without merging**
