### PR TITLE
adding proxy authentication in GeoApiContext

### PR DESCRIPTION
**Pull request by lhomme-a**
its a pull request for issue #336  proxy authentication in GeoApiContext
it can close also the reopened issue #141

### CODE REVIEW

**Comment by lhomme-a** [comment]
I signed it!

De : googlebot [mailto:notifications@github.com]
Envoyé : jeudi 17 août 2017 14:49
À : googlemaps/google-maps-services-java
Cc : LHOMME Alain; Author
Objet : Re: [googlemaps/google-maps-services-java] adding proxy authentication in GeoApiContext (#337)


Thanks for your pull request. It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://cla.developers.google.com/ to sign.

Once you've signed, please reply here (e.g. I signed it!) and we'll verify. Thanks.

________________________________

  *   If you've already signed a CLA, it's possible we don't have your GitHub username or you're using a different email address. Check your existing CLA data<https://cla.developers.google.com/clas> and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.
  *   If your company signed a CLA, they designated a Point of Contact who decides which employees are authorized to participate. You may need to contact the Point of Contact for your company and ask to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the project maintainer to go/cla#troubleshoot.
  *   In order to pass this check, please resolve this problem and have the pull request author add another comment and the bot will run again.

**Comment by domesticmouse** [comment]
Is there a way of adding some form of test over this additional functionality?

**Comment by domesticmouse** [comment]
Also, please run `./gradlew googleJavaFormat` to format your java code to the Google java formatting rules. Thanks!

**Comment by domesticmouse** [comment]
Sounds good to me, thank you for your PR!

**Comment by Falydoor** [comment]
Any idea when this feature will be pushed to maven (with version 0.2.3 I guess) ?

Thank you !

**Pull request merged**
