### PR TITLE
Support `nearestRoads` API call

### PR DESCRIPTION
**Pull request by dancingrobot84**

### CODE REVIEW

**Comment by dancingrobot84** [comment]
I signed it. The corporation's name is "Noa Technologies"

**Comment by domesticmouse** [comment]
At this point it looks like the Noa Technologies CLA is not associated with your GitHub account. I can't accept your PR until you have done so.

**Comment by dancingrobot84** [comment]
Thanks for letting me know. Could you please tell me what piece of the puzzle is missing? The CLA is signed by authorized signer, my work email (nikolai@noa.one) is in authorized contributors list and in both commits of this PR.

**Comment by domesticmouse** [comment]
The issue is that we have nikolai@noa.one's CLA on file, not dev@niko.tech, which is the email address exposed for this Github account.

**Comment by domesticmouse** [comment]
Accepted this PR as we have a CLA for nikolai@noa.one, the author of the PR's.

**Pull request merged**
