### PR TITLE
./gradlew googleJavaFormat

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by apjanke** [comment]
Quick question: this was to get the code to conform to the [Google Java Style Guide](https://google.github.io/styleguide/javaguide.html), which this project tries to adhere to, right?

**Comment by domesticmouse** [comment]
Yup. See [https://github.com/google/google-java-format](google-java-format) for more detail.

**Comment by apjanke** [comment]
Cool, thanks.

Would you entertain a Pull Request to get this project's Javadoc phrasing to better match the Style Guide, too?

**Comment by domesticmouse** [comment]
Absolutely. We gladly review all PRs =)

**Comment by apjanke** [comment]
Okay, PRs coming up. First one: https://github.com/googlemaps/google-maps-services-java/pull/315

**Pull request merged**
