### PR TITLE
Alternative to OkHttp based on GaeHttpTransport

### PR DESCRIPTION
**Pull request by ZiglioNZ**
Take it as is, it works for me on GAE.
See https://github.com/googlemaps/google-maps-services-java/issues/47

### CODE REVIEW

**Comment by ZiglioNZ** [comment]
I signed it

**Comment by clembo590** [comment]
WHY IS IT NOT MERGED IN THE MAIN BRANCH!

I GOT THE SOURCES AND MANAGED TO INTEGRATE IT IN 25 MINUTES.

I DID NOT TEST IT A LOT BUT THE FEW REQUESTS I DID USING APP ENGINE WORKED.

PLEASE MERGE IT IN THE MAIN BRANCH

**Comment by ZiglioNZ** [comment]
Hey why shouting? Unfortunately there's some more work needed as it's not currently possible to switch between OkHTTP and the GAE's UrlFetcher. So you can use it by simply adding these classes to your code and therefore overriding the library ones

**Comment by medvegy** [comment]
I would like to know when I can expect this to be merged into master?

**Comment by medvegy** [comment]
I have managed to use 'com.google.api-client:google-api-client:1.21.0' library as a http client instead of direct use of the URLFetchService. Another Google APIs are using that library so it's more convenient to use. The google-api-client has support for AppEngine as well and it works out of the box (together with google-api-client-appengine). If you want can send you a patch.

**Comment by domesticmouse** [comment]
As this PR whole sale replaces OkHttp with GAE functionality, it won't be merged as is, but we will happily review an update of this PR that makes the choice of OkHttp vs GAE dependent on deployment platform.

**Comment by boaty82** [comment]
when is this review likely to occur?

have also used this library for Distance Matrix, dropped in my wrapper library to GAE project and doesn't work ;o(

**Comment by medvegy** [comment]
Here is a IntelliJ IDEA patch
[google-api-client-replacement.patch.zip](https://github.com/googlemaps/google-maps-services-java/files/148383/google-api-client-replacement.patch.zip)

**Comment by boaty82** [comment]
Thanks for the patch. But am using gradle to pull in this project as a dependency

Also. Noticed that the services were throwing exception (yuk) why don't you create your own exception type (typed it runtime) instead?

**Comment by boaty82** [comment]
Medvedgy. The exception comment wasn't meant at you by the way but the author of the code

**Comment by domesticmouse** [comment]
@boaty82 please open a new issue for the thrown exception issue and detail your suggestion. For what it's worth, sending in a good PR with the fix is the quickest way to get things resolved (hint hint)

**Comment by domesticmouse** [comment]
Hey ZiglioNZ, can you please re-sign the CLA? My internal tools are claiming that you haven't signed the CLA. Thanks!

**Comment by ZiglioNZ** [comment]
Hi @domesticmouse, 

I'll try again, the first time it complained I wasn't a manager. I guess I'll autopromote myself just for this occasion (no pay rise, unfortunately). Will try again

**Comment by domesticmouse** [comment]
Thanks @ZiglioNZ!

**Comment by ZiglioNZ** [comment]
Ok, I've submitted a CLA again, both as myself and on behalf of my employer, I hope it works this time!

**Comment by ZiglioNZ** [comment]
Oh, I see the problem: I must have not set my e-mail address in eGit, back a year ago when I made this commit, annoying. Sorry everyone. Not sure how to rectify this.

**Comment by domesticmouse** [comment]
This code was integrated in https://github.com/googlemaps/google-maps-services-java/pull/154

**Pull request closed without merging**
